version: "3.9"
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
  
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER = user
      - POSTGRES_PASSWORD = password
      - POSTGRES_DB = database